### ISSUE TITLE
APKで配布してほしい

### ISSUE THREAD

**Issue by 0x307e** [Kadoshita/NiticWiFiAuth#1]
誰でも簡単にインストールできるようにビルド不要なAPKファイルで配布してほしいです。

**Comment by kadoshita** [comment]
@MakotiaFrontia 一応あります。
[https://github.com/Kadoshita/NiticWiFiAuth/blob/master/app/app-release.apk](https://github.com/Kadoshita/NiticWiFiAuth/blob/master/app/app-release.apk)
releaseのところに置いておきますね。
